name: Deploy Flask App

on:
  push:
    branches:
      - main  # Trigger deploy on push to the main branch

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r ./requirements.txt

      - name: Run Flask app
        run: |
          # Start Flask app on 0.0.0.0:5000
          FLASK_APP=app.py FLASK_RUN_HOST=0.0.0.0 FLASK_RUN_PORT=5000 flask run &  # Run in background
          sleep 5  # Wait for app to start

      - name: Run Full Set of Tests
        run: |
          curl http://localhost:5000  # Test if the Flask app is up and running
