name: Deploy Flask App

on:
  push:
    branches:
      - main  # Trigger deploy on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key for server access
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Flask app to server
        run: |
          # Copy files to server
          rsync -avz --exclude '.git' --exclude 'venv' ./ user@your-server-ip:/path/to/your/app/

          # SSH into the server to install dependencies and restart app
          ssh user@your-server-ip << 'EOF'
            cd /path/to/your/app
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart flask-app.service
          EOF
