name: Deploy Flask App

on:
  push:
    branches:
      - main  # Trigger deploy on push to the main branch


jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r ./requirements.txt

      - name: Run Full Set of Tests
        run: |
          python app.py
